import { addDoc, collection, doc, serverTimestamp, setDoc, updateDoc, writeBatch } from "firebase/firestore";
import { db } from "../lib/firebase";
import { normalizeText } from "../utils/normalization";
import type { Demand, DemandStatus, Priority, UserProfile } from "../types/models";

export async function createDemand(data:{title:string;description:string;screenName:string;formName:string;levelId:string;levelName:string;priority:Priority;companyId:string;requesterSector?:string},user:UserProfile,_initial?:DemandStatus){if(user.role==="requester"&&user.companyId!==data.companyId)throw new Error("Empresa inválida.");const ref=doc(collection(db,"demands"));const code=`DEM-${new Date().getFullYear()}-${ref.id.slice(0,6).toUpperCase()}`;await setDoc(ref,{...data,id:ref.id,code,sequence:null,year:new Date().getFullYear(),companyName:user.companyName??"Empresa",requesterId:user.uid,requesterName:user.name,requesterSector:data.requesterSector??"",screenNameNormalized:normalizeText(data.screenName),formNameNormalized:normalizeText(data.formName),status:"analysis",statusId:null,statusName:"Em análise",statusColor:"#3b82f6",consultantId:null,consultantName:null,createdBy:user.uid,updatedBy:user.uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),lastActivityAt:serverTimestamp(),schemaVersion:2});return ref.id;}
export async function changeDemandStatus(demand:Demand,status:DemandStatus,user:UserProfile,observation?:string){if(!observation?.trim())throw new Error("Informe uma observação.");const history=doc(collection(db,"demands",demand.id,"history"));const batch=writeBatch(db);batch.update(doc(db,"demands",demand.id),{status:status.legacyKeys?.[0]??"analysis",statusId:status.id,statusName:status.name,statusColor:status.color,statusHistoryId:history.id,statusUpdatedAt:serverTimestamp(),updatedBy:user.uid,updatedAt:serverTimestamp(),lastActivityAt:serverTimestamp()});batch.set(history,{type:"status",statusId:status.id,statusName:status.name,observation:observation.trim(),authorId:user.uid,authorName:user.name,createdAt:serverTimestamp()});await batch.commit();}
export async function saveStatusObservation(demand:Demand,user:UserProfile,observation:string){return addNote(demand.id,user,observation,false)}
export async function editStatusObservation(_demand?:Demand,_historyId?:string,_user?:UserProfile,_observation?:string){throw new Error("Edição de histórico indisponível no plano gratuito.")}
export async function acceptDemand(demand:Demand,consultant:UserProfile,workflowStatusIds:string[]){if(!consultant.companyIds?.includes(demand.companyId))throw new Error("Você não possui acesso a esta empresa.");await updateDoc(doc(db,"demands",demand.id),{consultantId:consultant.uid,consultantName:consultant.name,workflowStatusIds:[...new Set(workflowStatusIds)],updatedBy:consultant.uid,updatedAt:serverTimestamp(),lastActivityAt:serverTimestamp()})}
export async function updateDemandWorkflowStatuses(demand:Demand,consultant:UserProfile,workflowStatusIds:string[]){await updateDoc(doc(db,"demands",demand.id),{workflowStatusIds:[...new Set(workflowStatusIds)],updatedBy:consultant.uid,updatedAt:serverTimestamp()})}
export async function addNote(id:string,user:UserProfile,text:string,internal:boolean){if(!text.trim())throw new Error("Informe a observação.");await addDoc(collection(db,"demands",id,internal?"internalNotes":"publicNotes"),{text:text.trim(),authorId:user.uid,authorName:user.name,authorRole:user.role,createdAt:serverTimestamp(),edited:false})}
