import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import { useEffect, useState, type FormEvent } from "react";
import { db } from "../lib/firebase";
import { useAuth } from "../features/auth/AuthContext";
import { lookupCompanyByCnpj, saveCompany } from "../services/companies";
import type { Company } from "../types/models";
import { Page } from "./DashboardPage";

export function CompaniesManagementPage() {
  const { profile } = useAuth(); const [items,setItems]=useState<Company[]>([]),[showForm,setShowForm]=useState(false),[saving,setSaving]=useState(false),[lookupLoading,setLookupLoading]=useState(false),[message,setMessage]=useState("");
  useEffect(()=>onSnapshot(query(collection(db,"companies"),orderBy("legalName")),snapshot=>setItems(snapshot.docs.map(item=>({id:item.id,...item.data()}) as Company))),[]);
  async function lookup(form:HTMLFormElement){const cnpj=String(new FormData(form).get("cnpj")||"");setLookupLoading(true);setMessage("");try{const company=await lookupCompanyByCnpj(cnpj);const set=(name:string,value:string|undefined|null)=>{const input=form.elements.namedItem(name) as HTMLInputElement|null;if(input&&value)input.value=value};set("cnpj",company.cnpj);set("legalName",company.razao_social);set("tradeName",company.nome_fantasia);set("phone",company.ddd_telefone_1);set("email",company.email);set("zipCode",company.cep);set("street",company.logradouro);set("number",company.numero);set("complement",company.complemento);set("neighborhood",company.bairro);set("city",company.municipio);set("state",company.uf);setMessage(`Dados de ${company.razao_social} preenchidos pela BrasilAPI. Revise antes de salvar.`)}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível consultar o CNPJ.")}finally{setLookupLoading(false)}}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);setSaving(true);setMessage("");try{await saveCompany({legalName:String(data.get("legalName")).trim(),tradeName:String(data.get("tradeName")||"").trim(),cnpj:String(data.get("cnpj")||""),phone:String(data.get("phone")||"").trim(),email:String(data.get("email")||"").trim(),contactName:String(data.get("contactName")||"").trim(),notes:String(data.get("notes")||"").trim(),active:true,address:{zipCode:String(data.get("zipCode")||""),street:String(data.get("street")||""),number:String(data.get("number")||""),complement:String(data.get("complement")||""),neighborhood:String(data.get("neighborhood")||""),city:String(data.get("city")||""),state:String(data.get("state")||"")}});form.reset();setShowForm(false);setMessage("Empresa cadastrada com sucesso.")}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível cadastrar a empresa.")}finally{setSaving(false)}}
  if(profile?.role!=="admin")return <Page title="Acesso negado"><p>Área exclusiva de administradores.</p></Page>;
  return <Page title="Empresas" subtitle={`${items.length} empresa(s) cadastrada(s)`}><div className="toolbar"><p className="muted">Consulte o CNPJ para preencher os dados automaticamente.</p><button className="primary" onClick={()=>setShowForm(value=>!value)}>{showForm?"Fechar":"Nova empresa"}</button></div>{showForm&&<form className="form-grid panel" onSubmit={submit}><label>CNPJ<input name="cnpj" inputMode="numeric" placeholder="Somente números" onBlur={event=>lookup(event.currentTarget.form!)}/></label><div className="actions"><button type="button" disabled={lookupLoading} onClick={event=>lookup(event.currentTarget.form!)}>{lookupLoading?"Consultando…":"Preencher pelo CNPJ"}</button></div><label>Razão social *<input name="legalName" required/></label><label>Nome fantasia<input name="tradeName"/></label><label>Telefone<input name="phone"/></label><label>E-mail<input name="email" type="email"/></label><label>Contato<input name="contactName"/></label><label>CEP<input name="zipCode"/></label><label>Logradouro<input name="street"/></label><label>Número<input name="number"/></label><label>Complemento<input name="complement"/></label><label>Bairro<input name="neighborhood"/></label><label>Cidade<input name="city"/></label><label>UF<input name="state" maxLength={2}/></label><label className="wide">Observações<textarea name="notes" rows={3}/></label>{message&&<p className="notice wide">{message}</p>}<div className="actions wide"><button className="primary" disabled={saving}>{saving?"Salvando…":"Salvar empresa"}</button></div></form>}{!showForm&&message&&<p className="notice">{message}</p>}<div className="table-wrap"><table><thead><tr><th>Razão social</th><th>CNPJ</th><th>Cidade/UF</th><th>Status</th></tr></thead><tbody>{items.map(company=><tr key={company.id}><td>{company.legalName}</td><td>{company.cnpj||"—"}</td><td>{[company.address?.city,company.address?.state].filter(Boolean).join("/")||"—"}</td><td>{company.active?"Ativa":"Inativa"}</td></tr>)}</tbody></table></div></Page>;
}
